spring:
  datasource:
    url: jdbc:mariadb://azxca1731.synology.me:3306/summer
    driver-class-name: org.mariadb.jdbc.Driver
    username: summer
    password: rI5[w0vhFX
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    s3:
      bucket: kilometer-image
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: example
      secretKey: example