spring:
  datasource:
    url: jdbc:mariadb://database-1.c57d2zirnw4n.ap-northeast-2.rds.amazonaws.com/winter
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${my.database.username}
    password: ${my.database.password}
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        type:
          descriptor:
            sql: trace
        user_sql_comments: true
        format_sql: true
  properties:
    hibernate:
      type:
        descriptor:
          sql: trace
      user_sql_comments: true
      format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${client.id}
            client-secret: ${client.pw}
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            scope: email, profile_image, gender, id, birthyear, mobile, birthday
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
app:
  auth:
    tokenSecret: ${token.secret}
    tokenExpirationMsec: ${token.expiration.mesc}
  oauth2:
    authorizedRedirectDomain: kilometer.app
