spring:
  datasource:
    url: jdbc:mariadb://database-1.c57d2zirnw4n.ap-northeast-2.rds.amazonaws.com/winter
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${my.database.username}
    password: ${my.database.password}
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        type:
          descriptor:
            sql: trace
        user_sql_comments: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB