spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kilometer-test;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:

  flyway:
    enabled: false
#  batch:
#    job:
#      names: ${job.name:EMPTY}
#  datasource:
#    url: jdbc:mariadb://azxca1731.synology.me:3306/summer
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: summer
#    password: rI5[w0vhFX
#  jpa:
#    open-in-view: false
#    generate-ddl: false
#    show-sql: true
#    hibernate:
#      ddl-auto: validate
#
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    baseline-version: 0

crawler:
  selenium:
    remote-driver-url: ${selenium.server.url}
  target: # 뮤지컬, 전시, 콘서트 순
    yes24:
      origin: http://ticket.yes24.com
      category: http://ticket.yes24.com/New/Genre/GenreMain.aspx?genre=15457&Gcode=009_202_002 , http://ticket.yes24.com/New/Genre/GenreMain.aspx?genre=15460&Gcode=009_202_005, http://ticket.yes24.com/New/Genre/GenreMain.aspx?genre=15456&Gcode=009_202_001
    interpark:
      origin: https://tickets.interpark.com
      category: https://ticket.interpark.com/MusicalIndex.asp, https://ticket.interpark.com/LesIndex.asp, https://ticket.interpark.com/ConcertIndex.asp

cloud:
  aws:
    s3:
      bucket: kilometer-image
      folderName: api
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${s3.accessKey}
      secretKey: ${s3.secretKey}
