spring:
  batch:
    job:
      names: ${job.name:EMPTY}
  datasource:
    url: jdbc:mariadb://azxca1731.synology.me:3306/summer
    driver-class-name: org.mariadb.jdbc.Driver
    username: summer
    password: rI5[w0vhFX
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

crawler:
  selenium:
    remote-driver-url: http://61.73.21.98:10004
  target: # 뮤지컬, 전시, 콘서트 순
    yes24:
      origin: http://ticket.yes24.com
      category: http://ticket.yes24.com/New/Genre/GenreMain.aspx?genre=15457&Gcode=009_202_002 , http://ticket.yes24.com/New/Genre/GenreMain.aspx?genre=15460&Gcode=009_202_005, http://ticket.yes24.com/New/Genre/GenreMain.aspx?genre=15456&Gcode=009_202_001
