spring:
  datasource:
    url: jdbc:mariadb://azxca1731.synology.me:3306/summer
    driver-class-name: org.mariadb.jdbc.Driver
    username: summer
    password: rI5[w0vhFX
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  properties:
    hibernate:
      type:
        descriptor:
          sql: trace
      user_sql_comments: true
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
cloud:
  aws:
    s3:
      bucket: kilometer-image
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${s3.accessKey}
      secretKey: ${s3.secretKey}