spring:
  datasource:
    url: jdbc:mariadb://azxca1731.synology.me:3306/summer
    driver-class-name: org.mariadb.jdbc.Driver
    username: summer
    password: rI5[w0vhFX
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        type:
          descriptor:
            sql: trace
        user_sql_comments: true
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0